## Filtering

In [ ]:
import pandas as pd

d8 = pd.read_csv("D:\\Datasets\\multipleLinearRegression\\CarPrice_Assignment.csv")

# d8s = d8.iloc[:,:]
# d8s

# # d8s = pd.concat(d8, d8['carbody'])
# d8s= pd.concat([d8, d8['carbody']])
# d8s

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1.0,3.0,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,13495.0
1,2.0,3.0,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500.0
2,3.0,1.0,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500.0
3,4.0,2.0,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.40,10.0,102.0,5500.0,24.0,30.0,13950.0
4,5.0,2.0,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.40,8.0,115.0,5500.0,18.0,22.0,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,NaN,NaN,NaN,NaN,NaN,NaN,sedan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,NaN,NaN,NaN,NaN,NaN,NaN,sedan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,NaN,NaN,NaN,NaN,sedan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,NaN,NaN,NaN,NaN,NaN,NaN,sedan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,NaN,NaN,NaN,NaN,sedan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
carBody = str(input(f"Enter the type of body: "))
print(d8[d8['carbody'].str.contains(carBody, case=False)]) #Not working due to NaN vals
print(d8[d8['carbody']==carBody]) #Works, but returns all other fields as NaN, IDK why.

sedans= d8[d8['carbody']=='sedan'] #Again, returns other fields as NaN.
sedans

     car_ID  symboling          CarName fueltype aspiration doornumber  \
3         4          2      audi 100 ls      gas        std       four
4         5          2       audi 100ls      gas        std       four
5         6          2         audi fox      gas        std        two
6         7          1       audi 100ls      gas        std       four
8         9          1        audi 4000      gas      turbo       four
..      ...        ...              ...      ...        ...        ...
200     201         -1  volvo 145e (sw)      gas        std       four
201     202         -1      volvo 144ea      gas      turbo       four
202     203         -1      volvo 244dl      gas        std       four
203     204         -1        volvo 246   diesel      turbo       four
204     205         -1      volvo 264gl      gas      turbo       four

    carbody drivewheel enginelocation  wheelbase  ...  enginesize  fuelsystem  \
3     sedan        fwd          front       99.8  ...         109        mpfi
4     sedan        4wd          front       99.4  ...         136        mpfi
5     sedan        fwd          front       99.8  ...         136        mpfi
6     sedan        fwd          front      105.8  ...         136        mpfi
8     sedan        fwd          front      105.8  ...         131        mpfi
..      ...        ...            ...        ...  ...         ...         ...
200   sedan        rwd          front      109.1  ...         141        mpfi
201   sedan        rwd          front      109.1  ...         141        mpfi
202   sedan        rwd          front      109.1  ...         173        mpfi
203   sedan        rwd          front      109.1  ...         145         idi
204   sedan        rwd          front      109.1  ...         141        mpfi

     boreratio  stroke compressionratio horsepower  peakrpm citympg  \
3         3.19    3.40             10.0        102     5500      24
4         3.19    3.40              8.0        115     5500      18
5         3.19    3.40              8.5        110     5500      19
6         3.19    3.40              8.5        110     5500      19
8         3.13    3.40              8.3        140     5500      17
..         ...     ...              ...        ...      ...     ...
200       3.78    3.15              9.5        114     5400      23
201       3.78    3.15              8.7        160     5300      19
202       3.58    2.87              8.8        134     5500      18
203       3.01    3.40             23.0        106     4800      26
204       3.78    3.15              9.5        114     5400      19

     highwaympg    price
3            30  13950.0
4            22  17450.0
5            25  15250.0
6            25  17710.0
8            20  23875.0
..          ...      ...
200          28  16845.0
201          25  19045.0
202          23  21485.0
203          27  22470.0
204          25  22625.0

[96 rows x 26 columns]
     car_ID  symboling          CarName fueltype aspiration doornumber  \
3         4          2      audi 100 ls      gas        std       four
4         5          2       audi 100ls      gas        std       four
5         6          2         audi fox      gas        std        two
6         7          1       audi 100ls      gas        std       four
8         9          1        audi 4000      gas      turbo       four
..      ...        ...              ...      ...        ...        ...
200     201         -1  volvo 145e (sw)      gas        std       four
201     202         -1      volvo 144ea      gas      turbo       four
202     203         -1      volvo 244dl      gas        std       four
203     204         -1        volvo 246   diesel      turbo       four
204     205         -1      volvo 264gl      gas      turbo       four

    carbody drivewheel enginelocation  wheelbase  ...  enginesize  fuelsystem  \
3     sedan        fwd          front       99.8  ...         109        mpfi
4     sedan        4wd          front       99.4  ...         136        mpfi
5     sedan        fwd          front       99.8  ...         136        mpfi
6     sedan        fwd          front      105.8  ...         136        mpfi
8     sedan        fwd          front      105.8  ...         131        mpfi
..      ...        ...            ...        ...  ...         ...         ...
200   sedan        rwd          front      109.1  ...         141        mpfi
201   sedan        rwd          front      109.1  ...         141        mpfi
202   sedan        rwd          front      109.1  ...         173        mpfi
203   sedan        rwd          front      109.1  ...         145         idi
204   sedan        rwd          front      109.1  ...         141        mpfi

     boreratio  stroke compressionratio horsepower  peakrpm citympg  \
3         3.19    3.40             10.0        102     5500      24
4         3.19    3.40              8.0        115     5500      18
5         3.19    3.40              8.5        110     5500      19
6         3.19    3.40              8.5        110     5500      19
8         3.13    3.40              8.3        140     5500      17
..         ...     ...              ...        ...      ...     ...
200       3.78    3.15              9.5        114     5400      23
201       3.78    3.15              8.7        160     5300      19
202       3.58    2.87              8.8        134     5500      18
203       3.01    3.40             23.0        106     4800      26
204       3.78    3.15              9.5        114     5400      19

     highwaympg    price
3            30  13950.0
4            22  17450.0
5            25  15250.0
6            25  17710.0
8            20  23875.0
..          ...      ...
200          28  16845.0
201          25  19045.0
202          23  21485.0
203          27  22470.0
204          25  22625.0

[96 rows x 26 columns]

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
5,6,2,audi fox,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.0
6,7,1,audi 100ls,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.0
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [ ]:
# gassGuzzler = d8[d8['citympg']<20.0]

gassGuzzler = d8[(d8['citympg']<20.0) &
                 (d8['enginesize']>150)]
gassGuzzler
gassGuzzler.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
15,16,0,bmw x4,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760.0
16,17,0,bmw x5,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315.0
17,18,0,bmw x3,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880.0
29,30,3,dodge coronet custom (sw),gas,turbo,two,hatchback,fwd,front,95.9,...,156,mfi,3.60,3.90,7.0,145,5000,19,24,12964.0