## Aggregate Functions

Reduce a set of vals in a single summary val.
Used to summarize, organize data
Often used w/the groupby() function

In [24]:

import pandas as pd

d10 = pd.read_csv("D:\\Datasets\\multipleLinearRegression\\CarPrice_Assignment.csv")

d10

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

### Whole DataFrame Aggr. Funcs

In [2]:
# d10.mean()


wholeMean, wholeSum, wholeMin, wholeMax, wholeCount = d10.mean(numeric_only=True), d10.sum(numeric_only=True), d10.min(numeric_only=True), d10.max(numeric_only=True), d10.count()
# wholeMean, wholeSum, wholeMin, wholeMax, wholeCount = d10.mean(numeric_only=True), d10.sum(numeric_only=True), d10.min(numeric_only=True), d10.max(numeric_only=True), d10.count(numeric_only=True)
print(f"{wholeMean}\n\n{wholeSum}\n\n{wholeMin}\n\n{wholeMax}\n\n{wholeCount}")

car_ID                103.000000
symboling               0.834146
wheelbase              98.756585
carlength             174.049268
carwidth               65.907805
carheight              53.724878
curbweight           2555.565854
enginesize            126.907317
boreratio               3.329756
stroke                  3.255415
compressionratio       10.142537
horsepower            104.117073
peakrpm              5125.121951
citympg                25.219512
highwaympg             30.751220
price               13276.710571
dtype: float64

car_ID                21115.000
symboling               171.000
wheelbase             20245.100
carlength             35680.100
carwidth              13511.100
carheight             11013.600
curbweight           523891.000
enginesize            26016.000
boreratio               682.600
stroke                  667.360
compressionratio       2079.220
horsepower            21344.000
peakrpm             1050650.000
citympg                5170.000
highwaympg             6304.000
price               2721725.667
dtype: float64

car_ID                 1.00
symboling             -2.00
wheelbase             86.60
carlength            141.10
carwidth              60.30
carheight             47.80
curbweight          1488.00
enginesize            61.00
boreratio              2.54
stroke                 2.07
compressionratio       7.00
horsepower            48.00
peakrpm             4150.00
citympg               13.00
highwaympg            16.00
price               5118.00
dtype: float64

car_ID                205.00
symboling               3.00
wheelbase             120.90
carlength             208.10
carwidth               72.30
carheight              59.80
curbweight           4066.00
enginesize            326.00
boreratio               3.94
stroke                  4.17
compressionratio       23.00
horsepower            288.00
peakrpm              6600.00
citympg                49.00
highwaympg             54.00
price               45400.00
dtype: float64

car_ID              205
symboling           205
CarName             205
fueltype            205
aspiration          205
doornumber          205
carbody             205
drivewheel          205
enginelocation      205
wheelbase           205
carlength           205
carwidth            205
carheight           205
curbweight          205
enginetype          205
cylindernumber      205
enginesize          205
fuelsystem          205
boreratio           205
stroke              205
compressionratio    205
horsepower          205
peakrpm             205
citympg             205
highwaympg          205
price               205
dtype: int64

### Single Column Aggr. Funcs.

In [6]:
colMean = d10['carlength'].mean()
colSum = d10['carlength'].sum()
colMin = d10['carlength'].min()
colMax = d10['carlength'].max()
colCount = d10['carlength'].count()

print(f"\n{colMean, colSum, colMin, colMax, colCount}")
colMean, colSum, colMin, colMax, colCount

(np.float64(174.04926829268288), np.float64(35680.09999999999), np.float64(141.1), np.float64(208.1), np.int64(205))

(np.float64(174.04926829268288),
 np.float64(35680.09999999999),
 np.float64(141.1),
 np.float64(208.1),
 np.int64(205))

## GroupBy()

In [22]:
# groupItem = input("Enter group atrr.: ")
groupItem = 'carbody' #default
aGroup = d10.groupby(groupItem)
# aGroup.head() #Not useful here

print(aGroup.sum(numeric_only=True))
# print(aGroup.count(numeric_only=True))

             car_ID  symboling  wheelbase  carlength  carwidth  carheight  \
carbody
convertible     568         17      556.2     1022.3     393.5      308.6
hardtop        1007         15      788.0     1415.5     532.9      422.8
hatchback      6569        111     6687.5    11661.5    4567.3     3647.6
sedan          9799         32     9659.5    17048.2    6361.0     5216.4
wagon          3172         -4     2553.9     4532.6    1656.4     1418.2

             curbweight  enginesize  boreratio  stroke  compressionratio  \
carbody
convertible       16810         943      20.95   18.26             53.60
hardtop           22485        1410      28.87   26.58             85.80
hatchback        164373        8008     227.12  229.47            631.92
sedan            250617       12559     320.50  313.66           1050.00
wagon             69606        3096      85.16   79.39            257.90

             horsepower  peakrpm  citympg  highwaympg        price
carbody
convertible         790    30950      123         156   131343.000
hardtop            1138    40250      173         218   177668.000
hatchback          7082   366150     1842        2252   726365.667
sedan              9898   487850     2431        2960  1377050.000
wagon              2436   125450      601         718   309299.000

In [23]:
# groupItem = input("Enter group atrr.: ")
groupItem = 'fueltype' #default
aGroup = d10.groupby(groupItem)
# aGroup.head() #Not useful here

print(aGroup.sum(numeric_only=True))
# print(aGroup.count(numeric_only=True))
print(aGroup.mean(numeric_only=True))

aGroup.mean(numeric_only=True)

          car_ID  symboling  wheelbase  carlength  carwidth  carheight  \
fueltype
diesel      2512          2     2087.8     3640.2    1348.6     1116.7
gas        18603        169    18157.3    32039.9   12162.5     9896.9

          curbweight  enginesize  boreratio  stroke  compressionratio  \
fueltype
diesel         57976        2714      67.49   69.71            440.10
gas           465915       23302     615.11  597.65           1639.12

          horsepower  peakrpm  citympg  highwaympg        price
fueltype
diesel          1689    88700      606         695   316763.000
gas            19655   961950     4564        5609  2404962.667
              car_ID  symboling   wheelbase   carlength   carwidth  carheight  \
fueltype
diesel    125.600000   0.100000  104.390000  182.010000  67.430000  55.835000
gas       100.556757   0.913514   98.147568  173.188649  65.743243  53.496757

           curbweight  enginesize  boreratio    stroke  compressionratio  \
fueltype
diesel    2898.800000  135.700000   3.374500  3.485500         22.005000
gas       2518.459459  125.956757   3.324919  3.230541          8.860108

          horsepower     peakrpm   citympg  highwaympg       price
fueltype
diesel     84.450000  4435.00000  30.30000   34.750000  15838.1500
gas       106.243243  5199.72973  24.67027   30.318919  12999.7982

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
fueltype,,,,,,,,,,,,,,,,
diesel,125.600000,0.100000,104.390000,182.010000,67.430000,55.835000,2898.800000,135.700000,3.374500,3.485500,22.005000,84.450000,4435.00000,30.30000,34.750000,15838.1500
gas,100.556757,0.913514,98.147568,173.188649,65.743243,53.496757,2518.459459,125.956757,3.324919,3.230541,8.860108,106.243243,5199.72973,24.67027,30.318919,12999.7982